engines:
  structure:
    enabled: true
    channel: java
  duplication:
    enabled: true
    channel: cronopio
    config:
      languages:
        - java
exclude_paths:
  - "**.py"
  - "**.rb"
  - "**.js"
  - "**.jsx"
